package ooioo.ruches.evenement;

/**
 * Le type d'événement
 * Attention ne pas changer l'ordre. Il est utilisé en base de donnée.
 */
public enum TypeEvenement {
	RUCHEAJOUTRUCHER, AJOUTESSAIMRUCHE, 
	HAUSSEPOSERUCHE, HAUSSERETRAITRUCHE, HAUSSEREMPLISSAGE, 
	ESSAIMTRAITEMENT, ESSAIMTRAITEMENTFIN, ESSAIMSUCRE,
	COMMENTAIRERUCHE, COMMENTAIREHAUSSE, COMMENTAIREESSAIM, COMMENTAIRERUCHER,
	ESSAIMDISPERSION, RUCHEPESEE, RUCHECADRE
}
