# Cache des dépendances téléchargées entre builds successifs.
cache:
  paths:
    - .m2/repository

default:
  image: maven:3.8.4-openjdk-17 
build-job:
  stage: build
  when: manual
  script:
    - mvn package